[book]
authors = ["Dmitry Ivanov", "Anastasia Lysenko", "Elena Ivanova", "Asya Vinogradova"]
language = "en"
multilingual = false
src = "src"
title = "Lingwa de Planeta Grammar with Examples"

[build]
build-dir = "docs"

[output.html.fold]
enable = true